spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.provider_class: org.hibernate.cache.EhCacheProvider
      #hibernate.memcached.servers: 127.0.0.1:11211
  cache:
    memecache:
      host: 172.16.91.48
      port: 11211
system.application.domain: .miapc.org.cn

service.resource.url: https://sep.izhihuidao.com/ResourceLibrary.ApiHost/api/resourcetypes